version: '3.9'
services:
  mongo:
    image: mongo:7.0
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    environment:
       MONGO_INITDB_ROOT_USERNAME: hrms 
       MONGO_INITDB_ROOT_PASSWORD: hrms  
       MONGO_INITDB_DATABASE: hrms 
volumes:
  mongodb: {}